# this sets up a database to host the dataversion: '3.1'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # database admin gui
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_volume: {}